### ISSUE TITLE
Pikuma.com reference link is pointing to a boken link.

### ISSUE THREAD

**Issue by gustavopezzi** [BarbaraC12/raycast#1]
Hi there,

One of my students just mentioned that the link to the [pikuma.com](https://pikuma.com) website is broken in your README.

Thanks. :)

**Comment by BarbaraC12** [comment]
Hi Thank i'll fix it tomorowLe 30 mai 2021 19:42, Gustavo Pezzi ***@***.***> a écrit :
Hi there,
One of my students just mentioned that the link to the pikuma.com website is broken in your README.
Thanks. :)
